resolution: PS5000A_DR_8BIT
channel: PS5000A_CHANNEL_A
coupling: PS5000A_DC
vrange: PS5000A_5V
offset_v: 0.0

timebase: 1              # ~2 ns/sample on your unit (timebase 0 ≈ 1 ns)
samples: 100000
pre_ratio: 0.0           # immediate start, no pre-trigger

trig_enabled: false      # <— NEW: disable trigger for immediate capture
trig_source: PS5000A_CHANNEL_A
trig_level_mV: 500
trig_direction: PS5000A_RISING
auto_trig_ms: 0
trig_delay_samples: 0

csv_path: capture_100k_2ns.csv
write_chunk: 2000000     # irrelevant for 100k but fine
